/**
 * Metadata types for the FileMaker OData API.
 *
 * @see docs/05-metadata.md
 */

/** FileMaker-specific boolean field annotations. */
export interface FMBooleanAnnotations {
  AutoGenerated?: boolean;
  Index?: boolean;
  VersionID?: boolean;
  Global?: boolean;
  Calculation?: boolean;
  Summary?: boolean;
  Computed?: boolean;
}

/** FileMaker-specific value annotations. */
export interface FMValueAnnotations {
  MaxRepetitions?: number;
  ExternalSecurePath?: string;
  BestRowID?: string;
  RowVersion?: string;
  TableID?: string;
  FieldID?: string;
  ScriptID?: string;
  FMComment?: string;
  AIAnnotation?: string;
}

/** All FileMaker metadata annotations. */
export type FMAnnotations = FMBooleanAnnotations & FMValueAnnotations & {
  /** Product version (from Org.OData.Core.V1.ProductVersion). */
  ProductVersion?: string;
  /** Server version annotation (Claris 2026+). */
  ServerVersion?: string;
};

/** Edm property (field) in an entity type. */
export interface EdmProperty {
  name: string;
  type: string;
  nullable?: boolean;
  maxLength?: number;
  isKey?: boolean;
  repetitions?: number;
  annotations?: FMAnnotations;
}

/** Edm entity type (table definition). */
export interface EdmEntityType {
  name: string;
  tableId?: string;
  comment?: string;
  keys: string[];
  properties: EdmProperty[];
}

/** Edm entity set (table occurrence). */
export interface EdmEntitySet {
  name: string;
  entityType: string;
}

/** Edm action (FileMaker script). */
export interface EdmAction {
  name: string;
  scriptId?: string;
  isBound: boolean;
  parameterType?: string;
  returnType?: string;
}

/** Edm enum type (FileMaker value list). */
export interface EdmEnumType {
  name: string;
  members: { name: string; value: string | number }[];
}

/** Parsed OData metadata document. */
export interface ODataMetadata {
  namespace: string;
  entityTypes: EdmEntityType[];
  entitySets: EdmEntitySet[];
  actions: EdmAction[];
  enumTypes: EdmEnumType[];
  productVersion?: string;
  serverVersion?: string;
  raw: string;
}

/** FileMaker system fields. */
export const SYSTEM_FIELDS = {
  ROWID: 'ROWID',
  ROWMODID: 'ROWMODID',
} as const;

/** FileMaker immutable ID types. */
export type ImmutableIdType = 'FMTID' | 'FMFID' | 'FMSID';

/** FileMaker system tables. */
export const SYSTEM_TABLES = {
  TABLES: 'FileMaker_Tables',
  FIELDS: 'FileMaker_Fields',
  INDEXES: 'FileMaker_Indexes',
} as const;

/**
 * Extract the FileMaker Server major version from a product version string.
 * Returns null if the version cannot be determined.
 */
export function extractMajorVersion(productVersion: string | undefined): string | null {
  if (!productVersion) return null;
  // Match patterns like "19.0.1", "21.1.2", "22.0.1", "26.0.0"
  const match = productVersion.match(/^(\d+)\./);
  return match ? match[1] : null;
}
